-- require('onedark-config')
-- require('nord-config')
-- require('lualine-config')
-- require('tabline-config')
-- require('comment-config')
-- require('nvim-tree-config')
-- require('plugins')
require('keymaps')
require('plugins')
require('settings')
