#!/bin/sh

alias ls='ls -vh --group-directories-first --color=auto'
alias grep='grep --color=auto'
alias pwgen='pwgen -1cyns'
alias rm='rm -I'
# alias dotfiles='git --git-dir=$HOME/.dotfiles-new --work-tree=$HOME'
alias vim='nvim'
alias cf='cd ~/Documents/codeforces'
alias ctf='cd ~/Documents/ctf'
alias neofetch='fastfetch'
alias diff='diff --color=auto'
alias ip='ip -color'
