#!/bin/sh

if command -v exa &>/dev/null
then
	alias ls='exa --long --header --git'
else
	alias ls='ls --color=auto --group-directories-first -h'
fi

alias df='df -h'
alias du='du -h'
alias free='free -h'
alias grep='grep --color=auto'

alias freyr='docker run -it --rm -v $PWD:/data freyrcli/freyrjs'

alias v='nvim'
